import type { Metadata } from "next";
import { MainLayout } from "@/components/main-layout";
import FONT from "@/statics/font";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={FONT.className}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
